name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Node.js v8
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '8'
    
    - name: Yarn install
      run: yarn
    
    - name: Yarn lint
      run: yarn lint
  
    - name: TypeScript Compile
      run: yarn check-types
    
    - name: Yarn build
      run: yarn build
    

